from openai import OpenAI

def analyze_sentiment_per_query(query):
    prompt_sentiment_template = """Analyze the sentiment of the following query:
    
    "{query}"
    
    Please categorize the sentiment as Positive, Negative, or Neutral.
    """

    # Prepare the messages for the OpenAI API
    messages = [
        {"role": "user", "content": prompt_sentiment_template}
    ]
    
    client = OpenAI()
    # Step 4: Call OpenAI's API to perform trend analysis
    response = client.chat.completions.create(
        model="gpt-4o-mini",  # or other available models
        messages=messages,
        max_tokens=300
    )
     #Step 5: Return the insights generated by OpenAI
    return response.choices[0].message.content