from database.db_manager import DBManager
from openai import OpenAI

# Function to analyze data using OpenAI
def analyze_trends_with_openai():
    # Step 1: Retrieve data from SQL
    db_manager = DBManager()
    recent_queries = db_manager.get_recent_queries()
    db_manager.close_connection()

    if not recent_queries:
        return "No data available for trend analysis."

    # Step 2: Format data for OpenAI
    formatted_data = "\n".join([f"Query: {item['query']}, Intent: {item['intent']}" for item in recent_queries])

    # Step 3: Define the prompt for OpenAI to analyze trends
    prompt = f"""
    Here are the most recent user queries and their corresponding intents:
    
    {formatted_data}
    
    Please analyze this data and provide insights about the most common intents, emerging trends, and any patterns you can detect.
    """
# Prepare the messages for the OpenAI API
    messages = [
        {"role": "user", "content": prompt}
    ]

    client = OpenAI()
    # Step 4: Call OpenAI's API to perform trend analysis
    response = client.chat.completions.create(
        model="gpt-4o-mini",  # or other available models
        messages=messages,
        max_tokens=300
    )

    # Step 5: Return the insights generated by OpenAI
    return response.choices[0].message.content

# Example usage
trend_insights = analyze_trends_with_openai()
print(trend_insights)